### PR TITLE
Rubocop tweaks

### PR DESCRIPTION
**Pull request by 3flex**
- Disable the Metrics cops permanently - they're not useful
- Remove a couple of Style cops from the configuration that no longer flag errors

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @3flex, what do you think about migrating the config to [the one](https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/.rubocop.yml) we use in our modules?

**Comment by 3flex** [comment]
Could do. My only issue with that config file is all the cops that are marked explicitly enabled, when the upstream default configuration already enables them. It bloats the config unnecessarily IMHO. I prefer minimal configs.

I'm happy to go through that file and pare it down first? But if you want to use that file here, might as well. It makes sense to keep it consistent between projects.

**Comment by jyaworski** [comment]
@3flex we're verbose in that config for consistency's sake. We'd rather specify explicitly rather than assume upstream defaults which can (and do) change over time.

**Comment by 3flex** [comment]
I'll update this to use modulesync_config's configuration.

Does this gem support Ruby 1.8? It says it does in the current rubocop config, but modulesync_config's rubocop configuration enables support for Style/HashSyntax cop which enforces Ruby 1.9 style hashes.

**Comment by jyaworski** [comment]
@3flex we do not support 1.8 on any of our projects, officially. If anything happens to work on 1.8, that's cool.

**Pull request merged**
