### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by domcleal**
Will tag on merge.

### CODE REVIEW

**Comment by rnelson0** [comment]
Do we need any change log updates before the release?

**Comment by domcleal** [comment]
There isn't a changelog/history file for the project, but I could add one if you like. Otherwise I might just record it under [releases](https://github.com/voxpupuli/metadata-json-lint/releases) like I did last time.

**Comment by rnelson0** [comment]
It would be nice to have an actual changelog but no reason to hold things up if we have been operating without one for this long.

**Comment by domcleal** [comment]
Yep, I agree. I've written one using the past few release notes in #67.

The gem's now published, but I had to make a further change to the gemspec when I realised the published gem was missing the new file I added in lib/ - 1.2.1's now released with #66.

**Pull request merged**
